[package]
name = "pdfpackman"
version = "0.1.0"
authors = ["smeghead"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
printpdf = "0.3.2"
getopts = "0.2"
